import { ServiceCategory } from 'src/generated/prisma/client'

export const Services = [
	{
		name: 'Brushing Head Spa',
		description: 'Tratamento relaxante de head spa com brushing final.',
		price: 0,
		duration: 90,
		category: ServiceCategory.HAIR,
		featured: true,
	},
	{
		name: 'CH/Mass+Brushing',
		description: 'Chuveiro de massa com brushing incluído.',
		price: 0,
		duration: 90,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'CH/Mass+Cor Global S Amon',
		description: 'Chuveiro de massa com coloração global sem amoníaco.',
		price: 0,
		duration: 120,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'CH/Mass+Cor Raiz (S Amon)',
		description: 'Chuveiro de massa com coloração de raiz sem amoníaco.',
		price: 0,
		duration: 90,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'CH/Mass+Corte+Brushing',
		description: 'Chuveiro de massa com corte e brushing.',
		price: 0,
		duration: 120,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'CH/Mass+Corte+Finish (Homem)',
		description: 'Chuveiro de massa com corte e acabamento masculino.',
		price: 0,
		duration: 60,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Contrastes + Matização',
		description: 'Serviço de contrastes com matização final.',
		price: 0,
		duration: 150,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Cor 2 em 1 S Amon',
		description: 'Coloração 2 em 1 sem amoníaco.',
		price: 0,
		duration: 90,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Head Spa S/ Brushing',
		description: 'Tratamento de head spa sem brushing final.',
		price: 0,
		duration: 60,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Método Multivitamínico',
		description: 'Tratamento capilar com método multivitamínico.',
		price: 0,
		duration: 90,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Método Normalizante',
		description:
			'Tratamento capilar normalizante para reequilíbrio do couro cabeludo.',
		price: 0,
		duration: 90,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Método Regenerante',
		description: 'Tratamento capilar regenerante para cabelos danificados.',
		price: 0,
		duration: 90,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Método Revitalizante',
		description: 'Tratamento capilar revitalizante para cabelos sem brilho.',
		price: 0,
		duration: 90,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Método Sensitive',
		description: 'Tratamento capilar específico para couro cabeludo sensível.',
		price: 0,
		duration: 90,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Peeling Capilar',
		description: 'Peeling de couro cabeludo para remoção de impurezas.',
		price: 0,
		duration: 60,
		category: ServiceCategory.HAIR,
		featured: false,
	},
	{
		name: 'Sunlights + Matização',
		description: 'Técnica de sunlights com matização final.',
		price: 0,
		duration: 150,
		category: ServiceCategory.HAIR,
		featured: false,
	},

	// ==================== COLORAÇÃO ====================
	{
		name: 'Coloração',
		description: 'Coloração capilar completa com amoníaco.',
		price: 0,
		duration: 90,
		category: ServiceCategory.COLORING,
		featured: true,
	},
	{
		name: 'Tom Sobre Tom',
		description: 'Coloração tom sobre tom sem amoníaco para maior brilho.',
		price: 0,
		duration: 60,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Cor 2 em 1',
		description: 'Técnica exclusiva JLD de coloração 2 em 1.',
		price: 0,
		duration: 90,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Gloss 2 em 1',
		description: 'Tratamento gloss 2 em 1 para brilho intenso.',
		price: 0,
		duration: 60,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Contrastes',
		description: 'Técnica de contrastes para realçar o volume e luminosidade.',
		price: 0,
		duration: 150,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Contouring Contrastes',
		description: 'Técnica de contouring com contrastes para modelar o rosto.',
		price: 0,
		duration: 150,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Contrastes Overlight 2 Tons',
		description: 'Contrastes overlight em dois tons para efeito luminoso.',
		price: 0,
		duration: 180,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Magic Light',
		description: 'Técnica exclusiva JLD Magic Light para iluminação natural.',
		price: 0,
		duration: 180,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Gloss 100%',
		description: 'Tratamento gloss 100% para brilho e selagem da cor.',
		price: 0,
		duration: 45,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Root Shadow',
		description: 'Técnica de root shadow para efeito de raiz sombreada.',
		price: 0,
		duration: 90,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Arcticlight French Balayage',
		description: 'Técnica exclusiva Arcticlight com French Balayage.',
		price: 0,
		duration: 180,
		category: ServiceCategory.COLORING,
		featured: false,
	},
	{
		name: 'Sunlights',
		description: 'Técnica de sunlights para reflexos naturais e luminosos.',
		price: 0,
		duration: 150,
		category: ServiceCategory.COLORING,
		featured: false,
	},

	// ==================== TRATAMENTOS ====================
	{
		name: 'JLD Kera Molecular Bonder',
		description:
			'Tratamento de queratina molecular bonder para reconstrução profunda.',
		price: 0,
		duration: 90,
		category: ServiceCategory.TREATMENTS,
		featured: true,
	},
	{
		name: 'JLD Gokera Green',
		description:
			'Tratamento Gokera Green com fórmula natural para hidratação intensa.',
		price: 0,
		duration: 60,
		category: ServiceCategory.TREATMENTS,
		featured: false,
	},
	{
		name: 'JLD Gokera Repair',
		description:
			'Tratamento Gokera Repair para reparação de cabelos danificados.',
		price: 0,
		duration: 60,
		category: ServiceCategory.TREATMENTS,
		featured: false,
	},
	{
		name: 'JLD Gokera XXL',
		description:
			'Tratamento Gokera XXL para cabelos com necessidade de nutrição extrema.',
		price: 0,
		duration: 75,
		category: ServiceCategory.TREATMENTS,
		featured: false,
	},
	{
		name: 'JLD Gokera Color',
		description:
			'Tratamento Gokera Color para proteção e prolongamento de colorações.',
		price: 0,
		duration: 60,
		category: ServiceCategory.TREATMENTS,
		featured: false,
	},
	{
		name: 'JLD Gokera Liss',
		description:
			'Tratamento Gokera Liss para alisamento e disciplina dos fios.',
		price: 0,
		duration: 75,
		category: ServiceCategory.TREATMENTS,
		featured: false,
	},
	{
		name: 'JLD Gokera Blondie',
		description:
			'Tratamento Gokera Blondie especial para cabelos loiros e descolorados.',
		price: 0,
		duration: 60,
		category: ServiceCategory.TREATMENTS,
		featured: false,
	},

	// ==================== ESTÉTICA ====================
	{
		name: 'Depil. 1/2 Perna',
		description: 'Depilação de meia perna.',
		price: 0,
		duration: 30,
		category: ServiceCategory.AESTHETICS,
		featured: true,
	},
	{
		name: 'Depil. Axilas',
		description: 'Depilação de axilas.',
		price: 0,
		duration: 20,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
	{
		name: 'Depil. Buço',
		description: 'Depilação de buço.',
		price: 0,
		duration: 15,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
	{
		name: 'Depil. Perna Inteira',
		description: 'Depilação de perna inteira.',
		price: 0,
		duration: 45,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
	{
		name: 'Depil. Sobrancelhas',
		description: 'Depilação e design de sobrancelhas.',
		price: 0,
		duration: 20,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
	{
		name: 'Depil. Virilha Simples',
		description: 'Depilação de virilha simples.',
		price: 0,
		duration: 20,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
	{
		name: 'Depil. Virilhas Brasileiras',
		description: 'Depilação de virilhas brasileiras completa.',
		price: 0,
		duration: 30,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
	{
		name: 'Manicure',
		description: 'Serviço de manicure completo.',
		price: 0,
		duration: 45,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
	{
		name: 'Manicure+Gelinho',
		description: 'Manicure com aplicação de gelinho.',
		price: 0,
		duration: 60,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
	{
		name: 'Pedicure',
		description: 'Serviço de pedicure completo.',
		price: 0,
		duration: 60,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
	{
		name: 'Pedicure+Gelinho',
		description: 'Pedicure com aplicação de gelinho.',
		price: 0,
		duration: 75,
		category: ServiceCategory.AESTHETICS,
		featured: false,
	},
]
