import { Prisma } from 'src/generated/prisma/client'

export const Services = [
	{
		name: 'Brushing Head Spa',
		description: 'Tratamento relaxante de head spa com brushing final.',
		price: new Prisma.Decimal(0.0),
		duration: 90,
		category: 'Cabeleireiro',
	},
	{
		name: 'CH/Mass+Brushing',
		description: 'Chuveiro de massa com brushing incluído.',
		price: new Prisma.Decimal(0.0),
		duration: 90,
		category: 'Cabeleireiro',
	},
	{
		name: 'CH/Mass+Cor Global S Amon',
		description: 'Chuveiro de massa com coloração global sem amoníaco.',
		price: new Prisma.Decimal(0.0),
		duration: 120,
		category: 'Cabeleireiro',
	},
	{
		name: 'CH/Mass+Cor Raiz (S Amon)',
		description: 'Chuveiro de massa com coloração de raiz sem amoníaco.',
		price: new Prisma.Decimal(0.0),
		duration: 90,
		category: 'Cabeleireiro',
	},
	{
		name: 'CH/Mass+Corte+Brushing',
		description: 'Chuveiro de massa com corte e brushing.',
		price: new Prisma.Decimal(0.0),
		duration: 120,
		category: 'Cabeleireiro',
	},
	{
		name: 'CH/Mass+Corte+Finish (Homem)',
		description: 'Chuveiro de massa com corte e acabamento masculino.',
		price: new Prisma.Decimal(0.0),
		duration: 60,
		category: 'Cabeleireiro',
	},
	{
		name: 'Contrastes + Matização',
		description: 'Serviço de contrastes com matização final.',
		price: new Prisma.Decimal(0.0),
		duration: 150,
		category: 'Cabeleireiro',
	},
	{
		name: 'Cor 2 em 1 S Amon',
		description: 'Coloração 2 em 1 sem amoníaco.',
		price: new Prisma.Decimal(0.0),
		duration: 90,
		category: 'Cabeleireiro',
	},
	{
		name: 'Head Spa S/ Brushing',
		description: 'Tratamento de head spa sem brushing final.',
		price: new Prisma.Decimal(0.0),
		duration: 60,
		category: 'Cabeleireiro',
	},
	{
		name: 'Método Multivitamínico',
		description: 'Tratamento capilar com método multivitamínico.',
		price: new Prisma.Decimal(0.0),
		duration: 90,
		category: 'Cabeleireiro',
	},
	{
		name: 'Método Normalizante',
		description:
			'Tratamento capilar normalizante para reequilíbrio do couro cabeludo.',
		price: new Prisma.Decimal(0.0),
		duration: 90,
		category: 'Cabeleireiro',
	},
	{
		name: 'Método Regenerante',
		description: 'Tratamento capilar regenerante para cabelos danificados.',
		price: new Prisma.Decimal(0.0),
		duration: 90,
		category: 'Cabeleireiro',
	},
	{
		name: 'Método Revitalizante',
		description: 'Tratamento capilar revitalizante para cabelos sem brilho.',
		price: new Prisma.Decimal(0.0),
		duration: 90,
		category: 'Cabeleireiro',
	},
	{
		name: 'Método Sensitive',
		description: 'Tratamento capilar específico para couro cabeludo sensível.',
		price: new Prisma.Decimal(0.0),
		duration: 90,
		category: 'Cabeleireiro',
	},
	{
		name: 'Peeling Capilar',
		description: 'Peeling de couro cabeludo para remoção de impurezas.',
		price: new Prisma.Decimal(0.0),
		duration: 60,
		category: 'Cabeleireiro',
	},
	{
		name: 'Sunlights + Matização',
		description: 'Técnica de sunlights com matização final.',
		price: new Prisma.Decimal(0.0),
		duration: 150,
		category: 'Cabeleireiro',
	},

	// ==================== ESTÉTICA ====================
	{
		name: 'Depil. 1/2 Perna',
		description: 'Depilação de meia perna.',
		price: new Prisma.Decimal(0.0),
		duration: 30,
		category: 'Estética',
	},
	{
		name: 'Depil. Axilas',
		description: 'Depilação de axilas.',
		price: new Prisma.Decimal(0.0),
		duration: 20,
		category: 'Estética',
	},
	{
		name: 'Depil. Buço',
		description: 'Depilação de buço.',
		price: new Prisma.Decimal(0.0),
		duration: 15,
		category: 'Estética',
	},
	{
		name: 'Depil. Perna Inteira',
		description: 'Depilação de perna inteira.',
		price: new Prisma.Decimal(0.0),
		duration: 45,
		category: 'Estética',
	},
	{
		name: 'Depil. Sobrancelhas',
		description: 'Depilação e design de sobrancelhas.',
		price: new Prisma.Decimal(0.0),
		duration: 20,
		category: 'Estética',
	},
	{
		name: 'Depil. Virilha Simples',
		description: 'Depilação de virilha simples.',
		price: new Prisma.Decimal(0.0),
		duration: 20,
		category: 'Estética',
	},
	{
		name: 'Depil. Virilhas Brasileiras',
		description: 'Depilação de virilhas brasileiras completa.',
		price: new Prisma.Decimal(0.0),
		duration: 30,
		category: 'Estética',
	},
	{
		name: 'Manicure',
		description: 'Serviço de manicure completo.',
		price: new Prisma.Decimal(0.0),
		duration: 45,
		category: 'Estética',
	},
	{
		name: 'Manicure+Gelinho',
		description: 'Manicure com aplicação de gelinho.',
		price: new Prisma.Decimal(0.0),
		duration: 60,
		category: 'Estética',
	},
	{
		name: 'Pedicure',
		description: 'Serviço de pedicure completo.',
		price: new Prisma.Decimal(0.0),
		duration: 60,
		category: 'Estética',
	},
	{
		name: 'Pedicure+Gelinho',
		description: 'Pedicure com aplicação de gelinho.',
		price: new Prisma.Decimal(0.0),
		duration: 75,
		category: 'Estética',
	},
]
